// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/services/client/user_stored_data.go
//
// Generated by this command:
//
//	mockgen -source=./internal/services/client/user_stored_data.go -destination=./internal/services/client/mocks/user_stored_data.go
//
// Package mock_client is a generated GoMock package.
package mock_client

import (
	context "context"
	reflect "reflect"

	domain "github.com/MowlCoder/goph-keeper/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockcryptorForUserStoredDataService is a mock of cryptorForUserStoredDataService interface.
type MockcryptorForUserStoredDataService struct {
	ctrl     *gomock.Controller
	recorder *MockcryptorForUserStoredDataServiceMockRecorder
}

// MockcryptorForUserStoredDataServiceMockRecorder is the mock recorder for MockcryptorForUserStoredDataService.
type MockcryptorForUserStoredDataServiceMockRecorder struct {
	mock *MockcryptorForUserStoredDataService
}

// NewMockcryptorForUserStoredDataService creates a new mock instance.
func NewMockcryptorForUserStoredDataService(ctrl *gomock.Controller) *MockcryptorForUserStoredDataService {
	mock := &MockcryptorForUserStoredDataService{ctrl: ctrl}
	mock.recorder = &MockcryptorForUserStoredDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcryptorForUserStoredDataService) EXPECT() *MockcryptorForUserStoredDataServiceMockRecorder {
	return m.recorder
}

// DecryptBytes mocks base method.
func (m *MockcryptorForUserStoredDataService) DecryptBytes(crypted []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptBytes", crypted)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptBytes indicates an expected call of DecryptBytes.
func (mr *MockcryptorForUserStoredDataServiceMockRecorder) DecryptBytes(crypted any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptBytes", reflect.TypeOf((*MockcryptorForUserStoredDataService)(nil).DecryptBytes), crypted)
}

// EncryptBytes mocks base method.
func (m *MockcryptorForUserStoredDataService) EncryptBytes(raw []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptBytes", raw)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptBytes indicates an expected call of EncryptBytes.
func (mr *MockcryptorForUserStoredDataServiceMockRecorder) EncryptBytes(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptBytes", reflect.TypeOf((*MockcryptorForUserStoredDataService)(nil).EncryptBytes), raw)
}

// MockuserStoredDataRepository is a mock of userStoredDataRepository interface.
type MockuserStoredDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserStoredDataRepositoryMockRecorder
}

// MockuserStoredDataRepositoryMockRecorder is the mock recorder for MockuserStoredDataRepository.
type MockuserStoredDataRepositoryMockRecorder struct {
	mock *MockuserStoredDataRepository
}

// NewMockuserStoredDataRepository creates a new mock instance.
func NewMockuserStoredDataRepository(ctrl *gomock.Controller) *MockuserStoredDataRepository {
	mock := &MockuserStoredDataRepository{ctrl: ctrl}
	mock.recorder = &MockuserStoredDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserStoredDataRepository) EXPECT() *MockuserStoredDataRepositoryMockRecorder {
	return m.recorder
}

// AddData mocks base method.
func (m *MockuserStoredDataRepository) AddData(ctx context.Context, dataType string, data []byte, meta string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddData", ctx, dataType, data, meta)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddData indicates an expected call of AddData.
func (mr *MockuserStoredDataRepositoryMockRecorder) AddData(ctx, dataType, data, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddData", reflect.TypeOf((*MockuserStoredDataRepository)(nil).AddData), ctx, dataType, data, meta)
}

// CountUserDataOfType mocks base method.
func (m *MockuserStoredDataRepository) CountUserDataOfType(ctx context.Context, dataType string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUserDataOfType", ctx, dataType)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUserDataOfType indicates an expected call of CountUserDataOfType.
func (mr *MockuserStoredDataRepositoryMockRecorder) CountUserDataOfType(ctx, dataType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUserDataOfType", reflect.TypeOf((*MockuserStoredDataRepository)(nil).CountUserDataOfType), ctx, dataType)
}

// DeleteBatch mocks base method.
func (m *MockuserStoredDataRepository) DeleteBatch(ctx context.Context, ids []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockuserStoredDataRepositoryMockRecorder) DeleteBatch(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockuserStoredDataRepository)(nil).DeleteBatch), ctx, ids)
}

// DeleteByID mocks base method.
func (m *MockuserStoredDataRepository) DeleteByID(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockuserStoredDataRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockuserStoredDataRepository)(nil).DeleteByID), ctx, id)
}

// GetAll mocks base method.
func (m *MockuserStoredDataRepository) GetAll(ctx context.Context) ([]domain.UserStoredData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]domain.UserStoredData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockuserStoredDataRepositoryMockRecorder) GetAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockuserStoredDataRepository)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockuserStoredDataRepository) GetByID(ctx context.Context, id int) (*domain.UserStoredData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.UserStoredData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockuserStoredDataRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockuserStoredDataRepository)(nil).GetByID), ctx, id)
}

// GetWithType mocks base method.
func (m *MockuserStoredDataRepository) GetWithType(ctx context.Context, dataType string, filters *domain.StorageFilters) ([]domain.UserStoredData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithType", ctx, dataType, filters)
	ret0, _ := ret[0].([]domain.UserStoredData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithType indicates an expected call of GetWithType.
func (mr *MockuserStoredDataRepositoryMockRecorder) GetWithType(ctx, dataType, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithType", reflect.TypeOf((*MockuserStoredDataRepository)(nil).GetWithType), ctx, dataType, filters)
}

// UpdateByID mocks base method.
func (m *MockuserStoredDataRepository) UpdateByID(ctx context.Context, id int, data []byte, meta string) (*domain.UserStoredData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, id, data, meta)
	ret0, _ := ret[0].(*domain.UserStoredData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockuserStoredDataRepositoryMockRecorder) UpdateByID(ctx, id, data, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockuserStoredDataRepository)(nil).UpdateByID), ctx, id, data, meta)
}
